vpndata:
  image: busybox
  volumes:
    - /etc/openvpn
    - /tmp:/backup
  command: tar xvf /backup/backup.tar
vpnservice:
  image: kylemanna/openvpn
  volumes_from: 
    - vpndata
  ports: 
    - "1194:1194/udp"
  cap_add:
    - NET_ADMIN
